/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BioAvatar({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bioavatar.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.bird001.geometry} material={materials['uv.metallic.anim.matt']} position={[-0.25, 0, -0.01]} rotation={[-Math.PI, 1.21, -Math.PI]} scale={0.41} />
    </group>
  )
}

useGLTF.preload('/bioavatar.glb')
